services:
  database:
    image: postgres
    container_name: nex-digital
    restart: "no"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=nex-digital
    volumes:
      - pgdata:/data/postgres

# app:
#   build: .
#   container_name: db-api
#   restart: "no"
#   ports:
#     - 3333:3333
#     - 9229:9229
#   volumes:
#     - .:/usr/app
#   links:
#     - database
#     - redis
#   depends_on:
#     - database
#     - redis

volumes:
  pgdata:
    driver: local
